; PlatformIO Project Configuration File

[platformio]
default_envs = esp32
build_dir = /tmp/pio_build_universal
core_dir = /tmp/pio_core_universal
libdeps_dir = /tmp/pio_libdeps_universal

[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
board_build.partitions = min_spiffs.csv
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbserial-0001

build_flags =
    -D MQTT_MAX_PACKET_SIZE=512
    -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED=1
    -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED=1

lib_deps =
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    knolleary/PubSubClient @ ^2.8
    h2zero/NimBLE-Arduino @ ^1.4.3

[env:esp32_ota]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_protocol = espota
upload_port = universal-remote.local
upload_flags =
    --port=3232
    --auth=admin123

build_flags =
    -D MQTT_MAX_PACKET_SIZE=512

lib_deps =
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    knolleary/PubSubClient @ ^2.8
    h2zero/NimBLE-Arduino @ ^1.4.3

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags =
    -D MQTT_MAX_PACKET_SIZE=512

lib_deps =
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    knolleary/PubSubClient @ ^2.8

[env:nodemcuv2_ota]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_protocol = espota
upload_port = 192.168.10.22
upload_flags =
    --port=8266
    --auth=admin123

build_flags =
    -D MQTT_MAX_PACKET_SIZE=512

lib_deps =
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    knolleary/PubSubClient @ ^2.8
