[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8.0

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH

[env:nodemcuv2_ota]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_protocol = espota
upload_port = desk-lamp.local
upload_flags =
    --port=8266
    --auth=admin123

lib_deps =
    knolleary/PubSubClient @ ^2.8.0

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
